### ISSUE TITLE
Create Element Button not working on Table Arrangement

### ISSUE THREAD

**Issue by ChrisExtrem** [ysfchn/DynamicComponents-AI2#54]
![CapturaBloques](https://user-images.githubusercontent.com/8534379/158464856-2799dad1-9623-480a-b0bd-74d5bb090715.png)
![Captura de pantalla](https://user-images.githubusercontent.com/8534379/158464861-7f9de248-f624-470a-bf96-282ce1a3ddef.png)

**Comment by ysfchn** [comment]
Sorry for the long wait. Table arrangements have multiple rows and columns, and since there is not a parameter for that in the block, it simply won't work. And I'm not sure if I should add new parameters to Create block just for supporting Table arrangements. So, sadly, I prefer to not add support for it at this time.
